# Una aproximación a la estadística

Iniciemos con un sencillo problema relacionado con la calidad en algunos datos de costos digitados en un sistema, como medimos la calidad de estos datos? como deberíamos controlar la calidad de estos datos? @heumann2016 ,

Una empresa ha registrado la siguiente información de costo unitarios de un insumo médico "jeringas con agujas desechables", de esos datos @R-ggplot2 obtenemos una muestra de cien(100) valores digitados en diferentes fechas, esta información fue registrada con la calidad esperada?

| 383 \| 652 \| 652 \| 652 \| 383 \| 652 \| 652 \| 652 \| 383 \| 652 \|
| 652 \| 652 \| 383 \| 652 \| 652 \| 652 \| 383 \| 652 \| 652 \| 652 \|
| 383 \| 652 \| 652 \| 652 \| 383 \| 652 \| 652 \| 652 \| 383 \| 652 \|
| 652 \| 2223 \| 383 \| 652 \| 652 \| 50100 \| 383 \| 652 \| 652 \| 50100 \|
| 383 \| 652 \| 652 \| 50100 \| 383 \| 652 \| 652 \| 50100 \| 383 \| 652 \|
| 652 \| 79700 \| 383 \| 652 \| 652 \| 103900 \| 383 \| 652 \| 652 \| 103900 \|
| 383 \| 652 \| 652 \| 103900 \| 383 \| 652 \| 652 \| 103900 \| 383 \| 652 \|
| 652 \| 103900 \| 383 \| 652 \| 652 \| 103900 \| 383 \| 652 \| 652 \| 126400 \|
| 258 \| 652 \| 652 \| 126400 \| 258 \| 652 \| 652 \| 148700 \| 258 \| 652 \|
| 652 \| 251100 \| 652 \| 652 \| 652 \| 334800 \| 652 \| 652 \| 652 \| 769900 \|

## en R

```{r}
c(383,652,652,652,383,652,652,652,
383,652,652,
652,383,652,652,652,
383,652,652,652,383,652,652,652,383,
652,652,652,383,652,652,2223,383,652,652,
50100,383,652,652,50100,383,652,652,50100,383,652,652,
50100,383,652,652,79700,
383,652,652,103900,383,652,652,103900,
383,652,652,103900,383,652,652,103900,
383,652,652,103900,383,652,652,103900,
383,652,652,126400,258,652,652,126400,
258,652,652,148700,258,652,652,251100,
652,652,652,334800,652,652,652,769900) 
```

Para responder a esta pregunta estudiemos algunas definiciones

::: {#defmedia .definition}
La media aritmética de una variable se define como la suma de los valores de la variable multiplicados por su frecuencia relativa correspondiente

Si llamamos $X$ a la variable y $x_i$ los valores que puede tomar la variable, la media aritmética se nota por $\overline{x}$ y se define por

$$\overline{x}=\sum_{i=1}^kf_{i}x_{i}=\frac{1}{n}\sum_{i=1}^kn_{i}x_{i}$$ Si la variable $X$ es discreta se aplica directamente, si es continua se toma como valor $x_i$ , las marcas de clase de los intervalos y como frecuencias la de los intervalos
:::

**Propiedades**

La media de las diferencias a la media es cero es decir $$\sum_{i=1}^kf_{i}(x_{i}-\overline{x})=0$$

::: {.proof}
$$\sum_{i=1}^kf_{i}(x_{i}-\overline{x})= \sum_{i=1}^k(f_{i}x_{i}-f_i\overline{x})=\sum_{i=1}^kf_ix_i-\overline x\sum_{i=1}^kf_i=\overline{x}-\overline{x}=0 $$
:::

::: {.remark}
La media de las desviaciones al cuadrado de los valores de la variable respecto una constante k cualquiera, se hace mínima, cuando la constante es igual a la media aritmética ($k=\overline{x}$)  
:::


::: {.definition}
For a right triangle, if $c$ denotes the length of the hypotenuse and $a$ and $b$ denote the lengths of the other two sides, we have

$$a^2 + b^2 = c^2$$
:::

```{theorem pyth, name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have

$$a^2 + b^2 = c^2$$
```
